# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
    datasource:
        host: proxysql.master.meliseginf.com:6612
        db: ${LOCAL_DB_NAME}
        username: ${LOCAL_DB_USER}
        password: ${LOCAL_DB_PASS}
        initialization-mode: always

    jpa:
        show-sql: true
        hibernate:
            sql: debug
            ddl-auto: create-drop # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
            globally_quoted_identifiers: true
            type: trace
        database-platform: org.hibernate.dialect.MySQL8Dialect

server:
    port: 8080 # no cambiar en prod
