# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
    datasource:
        host: DB_MYSQL_DESAENV04_DATABASE_DATABASE_ENDPOINT
        db: database
        username: database_WPROD
        password: DB_MYSQL_DESAENV04_DATABASE_DATABASE_WPROD
        initialization-mode: always

    jpa:
        hibernate:
            ddl-auto: none # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
        database-platform: org.hibernate.dialect.MySQL8Dialect
