# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    host: proxysql.master.meliseginf.com:6612
    db: ${LOCAL_DB_NAME}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: create-drop # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
    database-platform: org.hibernate.dialect.MySQL8Dialect